#!/opt/anaconda/bin/python

import sys
import atexit
import os
import shutil

# import the ciop functions (e.g. copy, log)

import cioppy
ciop = cioppy.Cioppy()

# define the exit codes
SUCCESS = 0
ERR_CLEANUP = 2

# add a trap to exit gracefully
def clean_exit(exit_code):
    log_level = 'INFO'
    if exit_code != SUCCESS:
        log_level = 'ERROR'  
   
    msg = { SUCCESS: 'Processing successfully concluded',
            ERR_CLEANUP: 'Failed cleaning master folder'
           }
 
    ciop.log(log_level, msg[exit_code])  
    
def main():
    # Loops over all the inputs

    PROCESSDIR="/tmp"


    for inputfile in sys.stdin:
        # report activity in log
        ciop.log('INFO', 'The tmp master folder is: ' + inputfile)
 
        processfolder = inputfile.replace("\t","").replace("\n","").replace("\r","")
  
        # publish the result 
        # ciop.publish copies the data retrieved  to the distributed filesystem (HDFS)
        #ciop.log('INFO', 'Publishing result')
        #published = ciop.publish(retrieved)
        #published = ciop.publish(os.path.join(processfolder,'patch.list')
        #ciop.log('INFO', 'Published ' + published)
        
        if os.path.exists(processfolder):
            ciop.log('INFO', 'Removing tmp master folder ' + processfolder)    
            #shutil.rmtree(processfolder)
    
try:
    main()
except SystemExit as e:
    if e.args[0]:
         clean_exit(e.args[0])
    raise
else:
    atexit.register(clean_exit, 0)
